repos:
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
        args: ['--baseline', '.secrets.baseline']
        exclude: |
          (?x)^(
            tests/.*|
            .*test.*\.py|
            .*_test\.py|
            test_.*\.py|
            .*\.md|
            .*\.txt|
            .*\.json|
            .*fixtures.*
          )$
  
  - repo: https://github.com/PyCQA/bandit
    rev: 1.8.0
    hooks:
      - id: bandit
        args: ['-r', 'src/', '-f', 'json', '-o', 'bandit-report.json']
        exclude: tests/
  
  - repo: local
    hooks:
      - id: safety-check
        name: Safety vulnerability scan
        entry: python
        args: ['-m', 'safety', 'scan', '--json', '--output', 'safety-report.json']
        language: system
        pass_filenames: false
        files: requirements.*\.txt$
  
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.4
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format
  
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.13.0
    hooks:
      - id: mypy
        additional_dependencies: [types-all]
        exclude: tests/
  
  - repo: https://github.com/pytest-dev/pytest
    rev: 8.4.1
    hooks:
      - id: pytest
        args: ['tests/', '-x', '--tb=short']
