groups:
- name: sentiment-analyzer-alerts
  rules:
  - alert: HighErrorRate
    annotations:
      description: Error rate is above 10% for 2 minutes
      summary: High error rate detected
    expr: rate(http_requests_total{status=~"5.."}[5m]) > 0.1
    for: 2m
    labels:
      severity: critical
  - alert: HighLatency
    annotations:
      description: 95th percentile latency is above 1 second
      summary: High latency detected
    expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m]))
      > 1.0
    for: 5m
    labels:
      severity: warning
  - alert: ServiceDown
    annotations:
      description: Sentiment analyzer service is not responding
      summary: Service is down
    expr: up{job="sentiment-analyzer-pro"} == 0
    for: 1m
    labels:
      severity: critical
