apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sentiment-analyzer-pro
    version: v1.0.0
  name: sentiment-analyzer-pro
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sentiment-analyzer-pro
  template:
    metadata:
      labels:
        app: sentiment-analyzer-pro
    spec:
      containers:
      - env:
        - name: ENVIRONMENT
          value: production
        - name: LOG_LEVEL
          value: INFO
        image: sentiment-analyzer-pro:latest
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 30
        name: sentiment-analyzer
        ports:
        - containerPort: 5000
        readinessProbe:
          httpGet:
            path: /ready
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          limits:
            cpu: 1000m
            memory: 1Gi
          requests:
            cpu: 250m
            memory: 256Mi
