alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - alertmanager:9093
global:
  scrape_interval: 15s
rule_files:
- alert_rules.yml
scrape_configs:
- job_name: sentiment-analyzer-pro
  metrics_path: /metrics
  scrape_interval: 10s
  static_configs:
  - targets:
    - sentiment-analyzer-service:80
