apiVersion: v1
kind: Service
metadata:
  labels:
    app: sentiment-analyzer-pro
  name: sentiment-analyzer-service
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: sentiment-analyzer-pro
  type: ClusterIP
