apiVersion: v1
kind: Service
metadata:
  labels:
    app: sentiment-analyzer
  name: sentiment-analyzer-service
  namespace: sentiment-analyzer
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: sentiment-analyzer
  type: LoadBalancer
